### ISSUE TITLE
Error Snapshot : ImportError(u'Module import failed for Remarks Template (tailpos_sync.tailpos_sync.doctype.remarks_template.remarks_template Error: No module named remarks_template.remarks_template)',)

### ISSUE THREAD

**Issue by sammish** [bailabs/tailpos-sync#18]
Traceback
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1036, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 71, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 81, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 26, in get_meta
    meta = FormMeta(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 53, in load_assets
    self.load_templates()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 178, in load_templates
    module = load_doctype_module(self.name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 192, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for Remarks Template (tailpos_sync.tailpos_sync.doctype.remarks_template.remarks_template Error: No module named remarks_template.remarks_template)

Pyver
Python 2.7.15rc1: /home/frappe/frappe-bench/env/bin/python (prefix: /home/frappe/frappe-bench/env)

Exception
{
 "args": "(u'Module import failed for Remarks Template (tai... module named remarks_template.remarks_template)',)", 
 "message": "Module import failed for Remarks Template (tai... module named remarks_template.remarks_template)"
}

Locals
{
 "app": "u'tailpos_sync'", 
 "doctype": "u'Remarks Template'", 
 "e": "ImportError('No module named remarks_template.remarks_template',)", 
 "key": "(u'tailpos_sync', u'Remarks Template', u'', u'')", 
 "module": "u'TailPOS Sync'", 
 "module_name": "u'tailpos_sync.tailpos_sync.doctype.remarks_template.remarks_template'", 
 "prefix": "u''", 
 "suffix": "u''"
}

**Comment by sammish** [comment]
@iRaySpace @jiloysss please look this issue.

**Comment by sammish** [comment]
![Peek 2019-09-15 09-09](https://user-images.githubusercontent.com/12432802/64917384-9bc6ab00-d798-11e9-89c7-47c6d601d0c1.gif)
